---
- hosts: localhost

  tasks:


    - name: test github
      git:
        repo: https://github.com/UncoDong/Ansible-test.git
        dest: "/workspace/Ansibletest"
        update: yes
        force: yes


    - name: test cd
      shell: "cd /workspace"

    - name: test pwd
      shell: "pwd"

  