---
- hosts: localhost

  tasks:


    - name: clone repository
      git:
        repo: https://github.com/UncoDong/Ansible-test.git
        dest: "/workspace/Ansibletest"
        update: yes
        force: yes


    - name: install ftp
      shell: "cd /workspace"

    - name: install nginx
      shell: "pwd"

  